--!strict
-- external api globals/methods or things that aren't defined in the api dump

return {
	"declare P1: Player",
	"declare P2: Player",

	-- mirin template
	-- TODO: add the rest later
	"declare foreground: ActorFrame",
	"declare function aft(self: ActorFrameTexture)",
	"declare function sprite(self: Sprite)",
	"declare function backToSongWheel(message: string)",
	"declare scx: number",
	"declare scy: number",
	"declare sw: number",
	"declare sh: number",
	"declare dw: number",
	"declare dh: number",
}
